export const FETCH_ALL_BANNER_SUCCESS = 'FETCH_ALL_BANNER_SUCCESS';
export const FETCH_ALL_BANNER_FAILED = 'FETCH_ALL_BANNER_FAILED';
export const FETCH_ALL_MOVIE_SUCCESS = "FETCH_ALL_MOVIE_SUCCESS";
export const FETCH_ALL_MOVIE_FAILED = "FETCH_ALL_MOVIE_FAILED";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
